services:
  be:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    container_name: zahub-be
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  fe:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    container_name: zahub-fe
    ports:
      - "3000:80"
  bot:
    build:
      context: ./chatbot/
      dockerfile: Dockerfile.dev
    container_name: zahub-bot
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      be:
        condition: service_healthy
