FROM python:3.11-slim

WORKDIR /app

RUN apt update && apt install curl -y

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

ENV PYTHONPATH=/app

COPY ./app /app/app

CMD ["fastapi", "run", "--workers", "4", "app/main.py"]

