FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./app /app/app

ENV PYTHONPATH=/app

CMD ["fastapi", "run", "--port", "8001", "--workers", "1", "app/main.py"]
